# Generated by Django 2.0.7 on 2019-03-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章正文')),
                ('art_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='文章类别')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
                ('login_limit', models.DateTimeField(auto_now_add=True, verbose_name='限制登录时间')),
                ('err_cs', models.IntegerField(verbose_name='错误次数')),
                ('nickname', models.CharField(default='未命名', max_length=32, null=True, verbose_name='昵称')),
                ('gender', models.CharField(default='', max_length=2, null=True, verbose_name='性别')),
                ('introduce', models.CharField(max_length=255, null=True, verbose_name='自我介绍')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
    ]
