# Generated by Django 2.0.7 on 2019-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(null=True, protocol='ipv4'),
        ),
    ]
